### ISSUE TITLE
You are missing gstreamer-1.0-0.dll

### ISSUE THREAD

**Issue by Raj123456788** [vladkol/gstreamer-netcore#1]

**Comment by Raj123456788** [comment]
can you please add it?

**Comment by vladkol** [comment]
@Raj123456788 GStreamer and additional plugins you may need should be installed separately - just as they do it across all platforms. This is mentioned in the [prerequisites](https://github.com/vladkol/gstreamer-netcore#prerequisites). 
As you seem to be working on Windows, it should be a MiniGW-build of  GStreamer ([gstreamer-1.0-mingw-x86_64-1.16.2](https://gstreamer.freedesktop.org/data/pkg/windows/1.16.2/gstreamer-1.0-mingw-x86_64-1.16.2.msi)). 
In addition to default components, select "Gstreamer 1.0 libav wrapper".
You may also need to create GST_PLUGIN_PATH environment variable pointing to %GSTREAMER_1_0_ROOT_X86_64%\lib\gstreamer-1.0 (C:\gstreamer\1.0\x86_64\lib\gstreamer-1.0).

**Comment by vladkol** [comment]
If you want to distribute gstreamer with your application on Windows, there is a guide on that: [Windows deployment](https://gstreamer.freedesktop.org/documentation/deploying/windows.html?gi-language=c)

**Comment by Raj123456788** [comment]
@vladkol  Thanks you for above comments. I am still getting the same error. I installed MiniGW-buildofGstreamer a complete install and added GST_PLUGIN_PATH in system enviornment variables list. Please let me know if I am missing anything else.
![image](https://user-images.githubusercontent.com/16295521/89691150-0f940980-d8bd-11ea-8b79-aeb2ff797af6.png)

**Comment by Raj123456788** [comment]
I don't see  gstreamer-1.0-0.dll in C:\gstreamer\1.0\x86_64\lib\gstreamer-1.0

**Comment by vladkol** [comment]
Can you force x64 build? It may be that on Windows it’s x86 by default (with AnyCPU).

**Comment by vladkol** [comment]
Also, gstreamer-1.0-0.dll should be in C:\gstreamer\1.0\x86_64\bin, and that folder needs to be added to PATH environment variable.

**Comment by Raj123456788** [comment]
I tried Building the gstreamer-netcore under x64. Still getting the same error.

**Comment by Raj123456788** [comment]
In addition to default components, select "Gstreamer 1.0 libav wrapper: Never got a option to install this. Please let me know how can I install this?

**Comment by vladkol** [comment]
When you install gstreamer-1.0-mingw-x86_64-1.16.2.msi, choose Custom installation, there will be libav wrapper component in it. If you did a complete install, this component was installed then. Please make sure GStreamer binary folder (C:\gstreamer\1.0\x86_64\bin by default) was been added to PATH environment variable. I'm not sure it happens on Windows by default.

**Comment by Raj123456788** [comment]
Yup I got the .dll but it is throwing the sqame error as above image. Crashing in Application.cs

**Comment by vladkol** [comment]
Does *gst-launch-1.0* command work? 
Also, if you updated PATH variable, you may need to restart Visual Studio.

**Comment by Raj123456788** [comment]
yes  gst-launch-1.0 command works.  Yes, I restarted my Visual Studio 2019

**Comment by Raj123456788** [comment]
How does it get to .dll? [DllImport("gstreamer-1.0-0.dll", CallingConvention = CallingConvention.Cdecl)] through enviornmental variables?

**Comment by vladkol** [comment]
It's a bit more complicated because of different library names across different platforms. On Windows, it should be gstreamer-1.0-0.dll that is in a folder added to PATH environment variable (Windows takes care of finding it). If it still can't be loaded, and the calling app is built for x64, then there is a dependency that must be missing.

**Comment by Raj123456788** [comment]
Which platform did you test it on?OSX?

**Comment by Raj123456788** [comment]
I just want to run the Basic Tutorials under C#. Can you please recommend any other repo that for sure works on windows?

**Comment by vladkol** [comment]
I develop on macOS and Ubuntu. Testing on all 3 (Windows 10, macOS 10.15 and Ubuntu 18.04) during every CI build. 
I've just tested it manually on a fresh Windows 10 virtual machine, and everything worked as expected: 
- installed gstreamer-1.0-mingw-x86_64-1.16.2.msi 
- added C:\gstreamer\1.0\x86_64\bin to PATH variable (the user's one, so I don't have to re-login)
- cloned the repo 
- opened Console Sample in VS Code 
- Built and ran the sample successfully 
As an alternative, you may try [gstreamer-sharp](https://gitlab.freedesktop.org/gstreamer/gstreamer-sharp), although it doesn't support .NET Core, and despite working on Windows, not officially including Windows as a supported platform.

**Comment by Raj123456788** [comment]
Build & ran? You ran These commands:    git clone https://github.com/vladkol/gstreamer-netcore --recurse
cd gstreamer-netcore
dotnet build

what is the confirmation that I should be looking for?

**Comment by vladkol** [comment]
I opened samples/ConsoleSample in VS Code and ran it from there.

________________________________

**Comment by Raj123456788** [comment]
Netcore3ConsoleSample.csproj How do you run in VS code? Do you have VS 2019. Can you try running from it?

**Comment by vladkol** [comment]
“It works on my machine” in Visual Studio 2019. 
What installer did you use for GStreamer?

**Comment by Raj123456788** [comment]
Hey, I installed gstreamer-1.0-msvc-x86_64-1.16.2.msi and selected all the components to install.

**Comment by vladkol** [comment]
You installed an msvc build of gstreamer which is not supported. It should be a MiniGW build: https://gstreamer.freedesktop.org/data/pkg/windows/1.16.2/gstreamer-1.0-mingw-x86_64-1.16.2.msi

**Comment by Raj123456788** [comment]
When I install minigw there is no gstreamer-1.0-0.dll under C:\gstreamer\1.0\x86_64\bin

**Comment by vladkol** [comment]
There is libgstreamer-1.0-0.dll which does the same job, and gstreamer-netcore library resolver takes care of finding the right dll.

**Comment by Raj123456788** [comment]
I ran the Netcoreconsole3 and selected playback still getting same error 
![image](https://user-images.githubusercontent.com/16295521/89808747-726ce700-daef-11ea-834e-9c103a6d7d0b.png) can you please tell me where is this .dll located in your workspace?

**Comment by vladkol** [comment]
C:\gstreamer\1.0\x86_64\bin

**Comment by Raj123456788** [comment]
What versions of Giosharp & GlibSharp are you running? I have 3.22.25.74

**Comment by vladkol** [comment]
I have the same version

**Comment by Raj123456788** [comment]
C:\gstreamer\1.0\x86_64\bin I don't have the gstreamer-1.0.dll I cn see libgstreamer-1.0-0.dll.  Let me know what else I can try/?

**Comment by vladkol** [comment]
Yes, libgstreamer-1.0-0.dll is good.
Just to make sure, it’s not going not work if you just copy the dll to your app’s folder. Gstreamer has a lot of dependencies, and the entire C:\gstreamer\1.0\x86_64\bin should either be in PATH env variable or shipped with your app.

**Comment by Raj123456788** [comment]
ok, thanks for the help. But it is not working will try some other repo. Thanks!

**Comment by vladkol** [comment]
Let me know how it goes with another repo. I will look into the issue once I get some time to setup a Windows machine. Thank you!

**Comment by Raj123456788** [comment]
The path variable in the enviornmental variables need to have the C:\gstreamer\1.0\x86_64\bin. This was required: Sorry if I missed it. Also https://gitlab.freedesktop.org/gstreamer/gstreamer-sharp/issues/26 had to roll down version to 1.14.5. That worked!

**Comment by Raj123456788** [comment]
thanks for the help!

**Comment by Raj123456788** [comment]
Getting Error: EntryPointNotFoundException: Unable to find an entry point named 'gst_video_aggregator_get_type' in DLL 'gstvideo-1.0-0.dll'. for raw samples. Do I need to install the a MiniGW build? What is difference between MiniGW &  gstreamer-1.0-x86-1.14.5.msi

**Comment by vladkol** [comment]
If might be that you are using a version of C# wrapper that is not compatible with your version of GStreamer. I’ve only tested with MiniGW build, and even gstreamer-sharp doesn’t seem to have MSVC compatibility complete.

________________________________

**Comment by Raj123456788** [comment]
Hey Buddy, any idea why this is happening? Also how does one get stride from gstbuffer or gstmemory ?
![tempsnip](https://user-images.githubusercontent.com/16295521/89958843-cd860300-dbef-11ea-8c30-c02267552e37.png)

**Comment by martingra** [comment]
Any update on this? 

I am getting the exception when runing the Parse.Launch() method.

I follow the instruction to install gstreamer in windows, but getting this exception.

**Comment by Raj123456788** [comment]
@martingra: You need to add The path variable in the environmental variables need to have the C:\gstreamer\1.0\x86_64\bin.
also make sure you have all the libs & .dll on your machine under "C:\gstreamer\1.0\x86_64\". I had to install multiple installers to get all things I needed. let me know details I can look into it.

**Comment by martingra** [comment]
@Raj123456788: Thanks for your answer! I follow the instructions, doing the following:

1) As I am working in windows, I installed the suggested msi in the documentation (https://gstreamer.freedesktop.org/data/pkg/windows/1.16.2/gstreamer-1.0-mingw-x86_64-1.16.2.msi).
I made the "complete" installation to have it all. I also tried installing the "devel" version from https://gstreamer.freedesktop.org/data/pkg/windows/1.16.2/.
2) I added to my PATH environment variable, the following:
- H:\gstreamer\1.0\x86_64\bin
- H:\gstreamer\1.0\x86_64\lib\gstreamer-1.0

As mentioned before in this thread, I can't see the gstreamer-1.0.0.dll, but I can see libgstreamer-1.0-0.dll.

Do you remember which version of gstreamer you installed?

From [here](https://github.com/vladkol/gstreamer-netcore/issues/1#issuecomment-671604389) I understand that you installed version 14, but I can't find a mingw version in https://gstreamer.freedesktop.org/data/pkg/windows/ for any of the 14 folders.

Thanks for your help!

**Comment by Raj123456788** [comment]
@martingra : Install MiniGW of 1.17.1 make sure you select all and not custom.
Change the Director name H:\gstreamer\1.0\x86_64 to H:\gstreamer\1.0\x86_64_1
Now Install Dlevel for 1.17.1 and now copy the all the .dll to H:\gstreamer\1.0\x86_64

Now you have everythings libs &.dll that should be it. can you send me screenshot of exact error or your gst-launch cmd.
