### ISSUE TITLE
Support for .NET 6 and .NET 7 on Windows?

### ISSUE THREAD

**Issue by BTOdell** [vladkol/gstreamer-netcore#11]
The DLL loading workaround (due to the libraries being prefixed with "lib" even on Windows) doesn't activate on .NET 6 or .NET 7 because of the hardcoded `#if` checks: https://github.com/vladkol/gstreamer-netcore/blob/fe0b40a49bfc50dda95133d925e8fba5edcde6da/gst-netcore/ApplicationModuleInitializer.cs#L3

Can a more general preprocessor condition be used so that it's automatically compatible going forward without having to keep changing the code?

**Comment by BTOdell** [comment]
Reference to available preprocessor variables: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives

**Comment by djkunedo** [comment]
+1. Please add support for .net 6. Thanks!
