### ISSUE TITLE
RawSamplesAndPlaybackComplex Not working

### ISSUE THREAD

**Issue by Raj123456788** [vladkol/gstreamer-netcore#3]
Does not raise NewVideoSample & NewAudioSample. Valid Uri
private static string source = "https://dash.akamaized.net/akamai/bbb_30fps/bbb_30fps.mpd";

**Comment by Raj123456788** [comment]
Hey Buddy, you have been quiet for last couple of days?

**Comment by vladkol** [comment]
Apparently Windows decoders don't like this file somehow. Please use another one.
