### ISSUE TITLE
Sample buffer Unmap() not freeing memory?

### ISSUE THREAD

**Issue by IvensaMDH** [vladkol/gstreamer-netcore#7]
When using a pipeline with an appsink, I am unable to free memory with Unmap after extracting samples.

I am using a simple pipeline from a rtsp source:

`            var gstPipe = $"rtspsrc location=rtsp://xxx:xxx@x.x.x.x:554/xxx.sdp ! rtph264depay ! avdec_h264 ! videoconvert ! videorate ! video/x-raw,format=RGB,framerate=6/1 ! appsink name=appsink1";`

and attaching to the appsink with:

```
var pipeline = Parse.Launch(gstPipe) as Pipeline;
var appsink = new AppSink(pipeline.GetChildByName("appsink1").Handle)
{
    WaitOnEos = true,
    Drop = true,
    Sync = true,
    Qos = true,
    EmitSignals = true,
};
appsink.NewSample += OnNewSample;
```

```
private static void OnNewSample(object o, NewSampleArgs args)
{
    var appsink = o as AppSink;

    using var sample = appsink.TryPullSample(0);
    using var caps = sample.Caps;
    using var cap = caps[0];

    sample.Buffer.Map(out MapInfo map, MapFlags.Read);

    Console.WriteLine($"Sample {sampleNumber++}!");

    cap.GetInt("width", out int _width);
    cap.GetInt("height", out int _height);

    sample.Buffer.Unmap(map); //NOT WORKING
}
```

Am i missing something or is there a possible memory leak? I've tried using the suggested version 1.16.2 as well the newest 1.18.3

Any help is greatly appreciated

**Comment by vladkol** [comment]
@IvensaMDH Does it throw an exception? Or you observe a memory leak.

**Comment by IvensaMDH** [comment]
@vladkol No exceptions - in fact it _seems_ that everything is working perfectly - extracted samples looking good as well. However, i do observe a memory leak. As soon as `sample.Buffer.Map(out MapInfo map, MapFlags.Read);` is called, the leak starts. Perhaps below can help?

![image](https://user-images.githubusercontent.com/56653296/108816107-d6e82300-75b5-11eb-80f9-7da851f77480.png)

**Comment by vladkol** [comment]
I think this is the reason: https://github.com/GtkSharp/GtkSharp/pull/136

The version their NuGet packages we use is almost a year old. Time to update.

**Comment by IvensaMDH** [comment]
@vladkol yes, that might be it - are you able to update this nuget with a newer Gtk version? Much appreciated!

**Comment by IvensaMDH** [comment]
@vladkol I just tried building **gstreamer-netcore** with **gstreamer-sharp** master branch. Using the **gstreamer-sharp-netcore.dll** and the newest **v3.22.25.128 GioSharp** and **GLibSharp** nugets - leak is still there:
![image](https://user-images.githubusercontent.com/56653296/108847514-16c40000-75e0-11eb-83a8-5adf772449af.png)

**Comment by vladkol** [comment]
`GLib.TimeoutHandler` is an event delegate, not disposable, and often created as `someObject.SomeMethod(new GLib.TimeoutHandler)`, [here](https://github.com/GStreamer/gstreamer-sharp/blob/9d7f360da7e3e0b3cf16adef83778d358aa35da7/sources/generated/Gst/MiniObject.cs#L229) is an example. - TimeoutHandler is not a disposable, so it's a job for garbage collector because we still in a managed environment.
Gst.MiniObject is a different story.
I suspect that is coming from this line: `sample.Buffer.Map(out MapInfo map, MapFlags.Read)`, specifically from  `sample.Buffer`. because [this getter](https://github.com/GStreamer/gstreamer-sharp/blob/9d7f360da7e3e0b3cf16adef83778d358aa35da7/sources/generated/Gst/Sample.cs#L31) creates an Opaque object which is actually Disposable. 

My suggestion is to try adding `using var buffer = sample.Buffer` and then `buffer.Map(out MapInfo map, MapFlags.Read)`

**Comment by IvensaMDH** [comment]
Disposing sample, buffers or memory seems to have no additional effect. I've tested the application on Windows as well Ubuntu and the issue is the same - so not OS specific...

```
static void OnNewSample(object o, NewSampleArgs args)
{
    var appsink = o as AppSink;

    using var sample = appsink.TryPullSample(0);
    using var caps = sample.Caps;
    using var cap = caps[0];
    using var buffer = sample.Buffer;

    buffer.Map(out MapInfo map, MapFlags.Read);
    Console.WriteLine($"Sample received!");
    sample.Buffer.Unmap(map);

    GC.Collect(); //Even forcing GC does not work...
}
```

Forcing GC does not work either unfortunately.

I am not quite sure where to look next. If you have any further suggestions please let me know and i will dig deeper.

br,

EDIT:
I've created a sample application: [https://github.com/IvensaMDH/GstTest](https://github.com/IvensaMDH/GstTest)

**Comment by IvensaMDH** [comment]
Perhaps using below can be a temporary solution?     
```
var map = new byte[buffer.Size];
buffer.Extract(0, ref map);
```

br,

**Comment by IvensaMDH** [comment]
Finally figured it out ;)

In my application i was using `sample.Buffer.Unmap(map);` instead of `buffer.Unmap(map);` - using the sample.Buffer getter will apparently result in a dupe of the buffer each time.

Memory is now looking good!

Thank you
