### ISSUE TITLE
 initialization on mac

### ISSUE THREAD

**Issue by MCREAPER-dotcom** [vladkol/gstreamer-netcore#9]
I try to start my application on mac catalina 10.15.5.

I can not run my application, which works the same on Linux and Windows, based on Avalonia, it seems like I installed everything I need, but I get this error:

Unhandled exception. System.TypeInitializationException: The type initializer for 'Gst.Application' threw an exception.
—-> System.DllNotFoundException: Unable to load shared library 'gstreamer-1.0-0.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libgstreamer-1.0-0.dll, 1): image not found
at Gst.List.gst_value_list_get_type()
at Gst.List.get_GType()
at Gst.Application..cctor()
—- End of inner exception stack trace —-
at Gst.Application.Init()

I do not understand what is needed and how to connect in order for the application to work.

**Comment by MCREAPER-dotcom** [comment]
I solve this problem (export gstreamer/bin in PATH) but  i take other problem. 
i can't load libgstwebrtc-1.0.dylib in my application

**Comment by vladkol** [comment]
@MCREAPER-dotcom Do you have `get-plugins-bad` installed?

**Comment by MCREAPER-dotcom** [comment]
i try to installed it.
As i understand there is a problem in Glib because i install Gstreamer and Gstreamer-dev at official, and when i install with brew gs t-plugins-bad  i get this:
GLib-GObject-CRITICAL **: 04:40:35.857: g_param_spec_pool_lookup: assertion 'pool != NULL' failed

**Comment by MCREAPER-dotcom** [comment]
if use DYLD_PRINT_LIBRARIES can see that library load and unload 
![image](https://user-images.githubusercontent.com/54661115/121519453-65b06c80-c9fa-11eb-98c3-798b37aca86f.png)

**Comment by vladkol** [comment]
Looks like a version conflict to me. Similar to this https://github.com/sdroege/gstreamer-rs/issues/60

**Comment by MCREAPER-dotcom** [comment]
I can solve this problem launch gstreamer.fraameworks/share/gstreamer/gst-env like note and load this text in terminal
